# Traefik configuration for Local AI Packaged
# This replaces Caddy with Traefik as the reverse proxy

# Global configuration
api:
  dashboard: true
  insecure: true

# Entry points
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "ai-network"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Certificate resolvers
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: your-email@domain.com
#       storage: /etc/traefik/acme.json
#       httpChallenge:
#         entryPoint: web

# Logging
log:
  level: INFO

# Access logs
accessLog: {}

# Metrics
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true